#!/usr/bin/env python3
"""Regenerate skills/INDEX.md from each skills/*/SKILL.md frontmatter.
One row per skill: name | fires when | does NOT fire when (from the 'Do not use' clause).
Run from the repo root:  python3 scripts/gen-index.py
Exits 1 if any description lacks a 'Do not use' boundary clause or the index exceeds 60 lines."""
import pathlib, re, sys

root = pathlib.Path(__file__).resolve().parent.parent
rows, problems = [], []
for skill in sorted(root.glob("skills/*/SKILL.md")):
    text = skill.read_text(encoding="utf-8")
    m = re.match(r"---\n(.*?)\n---", text, re.S)
    if not m:
        problems.append(f"{skill}: no frontmatter"); continue
    fm = m.group(1)
    name = re.search(r"^name:\s*(.+)$", fm, re.M)
    desc = re.search(r"^description:\s*(.+)$", fm, re.M)
    if not (name and desc):
        problems.append(f"{skill}: missing name or description"); continue
    name, desc = name.group(1).strip(), desc.group(1).strip().strip('"').strip("'")
    if name != skill.parent.name:
        problems.append(f"{skill}: name '{name}' != folder '{skill.parent.name}'")
    parts = re.split(r"\bDo not use\b", desc, maxsplit=1)
    if len(parts) != 2:
        problems.append(f"{skill}: description has no 'Do not use' boundary clause"); continue
    fires = parts[0].strip().rstrip(".")
    nots = parts[1].strip().lstrip(":,; ").rstrip(".")
    nots = nots[0].upper() + nots[1:] if nots else nots
    rows.append(f"| {name} | {fires} | {nots} |")

out = [
    "# Skills index",
    "",
    "Always in context. When a row's *fires when* matches the task, read `~/.claude/skills/<name>/SKILL.md` and follow it. Generated by `scripts/gen-index.py`; do not edit by hand.",
    "",
    "| Skill | Fires when | Does NOT fire when |",
    "| --- | --- | --- |",
    *rows,
    "",
]
if len(out) > 60:
    problems.append(f"INDEX.md would be {len(out)} lines (limit 60)")
if problems:
    print("\n".join(problems), file=sys.stderr); sys.exit(1)
(root / "skills" / "INDEX.md").write_text("\n".join(out), encoding="utf-8")
print(f"wrote skills/INDEX.md: {len(rows)} skills, {len(out)} lines")
