#!/usr/bin/env python3
"""Regenerate skills/INDEX.md from each skills/*/SKILL.md frontmatter.
Model-invoked skills: one row each, name | fires when | does NOT fire when (from the 'Do not use' clause).
User-invoked skills (disable-model-invocation: true): a second, two-column table.
Run from the repo root:  python3 scripts/gen-index.py
Exits 1 if a model-invoked description lacks a 'Do not use' clause or the index exceeds 60 lines."""
import pathlib, re, sys

root = pathlib.Path(__file__).resolve().parent.parent
rows, user_rows, problems = [], [], []
for skill in sorted(root.glob("skills/*/SKILL.md")):
    text = skill.read_text(encoding="utf-8")
    m = re.match(r"---\n(.*?)\n---", text, re.S)
    if not m:
        problems.append(f"{skill}: no frontmatter"); continue
    fm = m.group(1)
    name = re.search(r"^name:\s*(.+)$", fm, re.M)
    desc = re.search(r"^description:\s*(.+)$", fm, re.M)
    if not (name and desc):
        problems.append(f"{skill}: missing name or description"); continue
    name, desc = name.group(1).strip(), desc.group(1).strip().strip('"').strip("'")
    if name != skill.parent.name:
        problems.append(f"{skill}: name '{name}' != folder '{skill.parent.name}'")
    if re.search(r"^disable-model-invocation:\s*true\s*$", fm, re.M):
        user_rows.append(f"| /{name} | {desc.rstrip('.')} |")
        continue
    parts = re.split(r"\bDo not use\b", desc, maxsplit=1)
    if len(parts) != 2:
        problems.append(f"{skill}: description has no 'Do not use' boundary clause"); continue
    fires = parts[0].strip().rstrip(".")
    nots = parts[1].strip().lstrip(":,; ").rstrip(".")
    nots = nots[0].upper() + nots[1:] if nots else nots
    rows.append(f"| {name} | {fires} | {nots} |")

out = [
    "# Skills index",
    "",
    "Always in context. When a row's *fires when* matches the task, Call the Skill tool with \"<name>\" and follow the skill. Generated by `scripts/gen-index.py`; do not edit by hand.",
    "",
    "| Skill | Fires when | Does NOT fire when |",
    "| --- | --- | --- |",
    *rows,
]
if user_rows:
    out += ["", "Type to invoke; the agent never starts these on its own.", "", "| Skill | What it does |", "| --- | --- |", *user_rows]
out.append("")
if len(out) > 60:
    problems.append(f"INDEX.md would be {len(out)} lines (limit 60)")
if problems:
    print("\n".join(problems), file=sys.stderr); sys.exit(1)
(root / "skills" / "INDEX.md").write_text("\n".join(out), encoding="utf-8")
print(f"wrote skills/INDEX.md: {len(rows)} model-invoked + {len(user_rows)} user-invoked skills, {len(out)} lines")
